module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary)",
        "primary-container": "var(--color-primary-container)",
        "primary-fixed": "var(--color-primary-fixed)",
        secondary: "var(--color-secondary)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        tertiary: "var(--color-tertiary)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        background: "var(--color-background)",
        surface: "var(--color-surface)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-tint": "var(--color-surface-tint)",
        "on-surface": "var(--color-on-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-background": "var(--color-on-background)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        outline: "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",
        error: "var(--color-error)",
      },
      fontFamily: {
        headline: ["Manrope"],
        display:  ["Manrope"],   // alias — fixes teacher panel font-display bug
        body:     ["Inter"],
      },
      fontSize: {
        "3xs": ["var(--font-size-3xs)", { lineHeight: "1rem"    }],
        "2xs": ["var(--font-size-2xs)", { lineHeight: "1rem"    }],
        xs:    ["var(--font-size-xs)",  { lineHeight: "1.25rem" }],
        sm:    ["var(--font-size-sm)",  { lineHeight: "1.5rem"  }],
        base:  ["var(--font-size-base)",{ lineHeight: "1.75rem" }],
        lg:    ["var(--font-size-lg)",  { lineHeight: "1.75rem" }],
        xl:    ["var(--font-size-xl)",  { lineHeight: "1.75rem" }],
        "2xl": ["var(--font-size-2xl)", { lineHeight: "2rem"    }],
        "3xl": ["var(--font-size-3xl)", { lineHeight: "2.25rem" }],
        "4xl": ["var(--font-size-4xl)", { lineHeight: "2.5rem"  }],
        "5xl": ["var(--font-size-5xl)", { lineHeight: "1.1"     }],
      },
    },
  },
  plugins: [],
};